services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  dmtoolkit-backend:
    image: ghcr.io/kynesilverhide/dmtoolkit-backend:latest
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      PORT: 3000
      FRONTEND_URL: ${FRONTEND_URL}
      ADMIN_DEFAULT_PASSWORD: ${ADMIN_DEFAULT_PASSWORD}
      ADMIN_DEFAULT_USERNAME: ${ADMIN_DEFAULT_USERNAME}
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - uploads:/app/uploads

  dmtoolkit-frontend:
    image: ghcr.io/kynesilverhide/dmtoolkit-frontend:latest
    ports:
      - "8080:80"
    depends_on:
      - dmtoolkit-backend
volumes:
  pgdata:
  uploads:
