#!/usr/bin/env python3
"""
Generates aidedd_standard_items.json from hardcoded SRD 5e data (French).
Produces the same schema as aidedd_magic_items.json.
Run: python generate_standard_items.py -o backend/src/data/aidedd_standard_items.json
"""
import argparse
import json
import re
import unicodedata
from datetime import datetime, timezone


def slugify(name: str) -> str:
    s = unicodedata.normalize("NFKD", name)
    s = "".join(ch for ch in s if not unicodedata.combining(ch))
    s = s.lower()
    s = re.sub(r"[''\u2019]", "-", s)
    s = re.sub(r"[^a-z0-9]+", "-", s)
    return re.sub(r"-+", "-", s).strip("-")


def item(name_fr, name_en, item_type, desc, price="", weight="", extra_list=None):
    sl = slugify(name_fr)
    sl_vo = slugify(name_en)
    list_data = {}
    if price:
        list_data["prix"] = price
    if weight:
        list_data["poids"] = weight
    if extra_list:
        list_data.update(extra_list)
    return {
        "name": name_fr,
        "slug": sl,
        "slug_vo": sl_vo,
        "name_vo": name_en,
        "detail_url": f"https://www.aidedd.org/dnd/equipement.php?vf={sl}",
        "item_type": item_type,
        "rarity": "commun",
        "requires_attunement": False,
        "attunement_detail": "",
        "description": desc,
        "description_html": f"<p>{desc}</p>",
        "source": "Player's Handbook (SRD)",
        "list_data": list_data,
    }


ITEMS = [
    # ─── ARMES SIMPLES DE CORPS À CORPS ────────────────────────────────────
    item("Gourdin", "Club",
         "Arme simple de corps à corps",
         "Dégâts : 1d4 contondant. Propriétés : légère.",
         "1 pa", "1 kg"),
    item("Dague", "Dagger",
         "Arme simple de corps à corps",
         "Dégâts : 1d4 perforant. Propriétés : finesse, légère, lancer (portée 6/18 m).",
         "2 po", "0,5 kg"),
    item("Gourdin lourd", "Greatclub",
         "Arme simple de corps à corps",
         "Dégâts : 1d8 contondant. Propriétés : à deux mains.",
         "2 pa", "5 kg"),
    item("Hachette", "Handaxe",
         "Arme simple de corps à corps",
         "Dégâts : 1d6 tranchant. Propriétés : légère, lancer (portée 6/18 m).",
         "5 po", "1 kg"),
    item("Javeline", "Javelin",
         "Arme simple de corps à corps",
         "Dégâts : 1d6 perforant. Propriétés : lancer (portée 9/36 m).",
         "5 pa", "1 kg"),
    item("Marteau léger", "Light Hammer",
         "Arme simple de corps à corps",
         "Dégâts : 1d4 contondant. Propriétés : légère, lancer (portée 6/18 m).",
         "2 po", "1 kg"),
    item("Masse d'armes", "Mace",
         "Arme simple de corps à corps",
         "Dégâts : 1d6 contondant.",
         "5 po", "2 kg"),
    item("Bâton", "Quarterstaff",
         "Arme simple de corps à corps",
         "Dégâts : 1d6 contondant. Propriétés : polyvalente (1d8).",
         "2 pa", "2 kg"),
    item("Serpe", "Sickle",
         "Arme simple de corps à corps",
         "Dégâts : 1d4 tranchant. Propriétés : légère.",
         "1 po", "1 kg"),
    item("Lance", "Spear",
         "Arme simple de corps à corps",
         "Dégâts : 1d6 perforant. Propriétés : lancer (portée 6/18 m), polyvalente (1d8).",
         "1 po", "1,5 kg"),

    # ─── ARMES SIMPLES À DISTANCE ────────────────────────────────────────────
    item("Arbalète légère", "Light Crossbow",
         "Arme simple à distance",
         "Dégâts : 1d8 perforant. Propriétés : munitions (portée 24/96 m), chargement, à deux mains.",
         "25 po", "2,5 kg"),
    item("Fléchette", "Dart",
         "Arme simple à distance",
         "Dégâts : 1d4 perforant. Propriétés : finesse, lancer (portée 6/18 m).",
         "5 pc", "—"),
    item("Arc court", "Shortbow",
         "Arme simple à distance",
         "Dégâts : 1d6 perforant. Propriétés : munitions (portée 24/96 m), à deux mains.",
         "25 po", "1 kg"),
    item("Fronde", "Sling",
         "Arme simple à distance",
         "Dégâts : 1d4 contondant. Propriétés : munitions (portée 9/36 m).",
         "1 pa", "—"),

    # ─── ARMES DE GUERRE DE CORPS À CORPS ──────────────────────────────────
    item("Hache d'armes", "Battleaxe",
         "Arme de guerre de corps à corps",
         "Dégâts : 1d8 tranchant. Propriétés : polyvalente (1d10).",
         "10 po", "2 kg"),
    item("Fléau d'armes", "Flail",
         "Arme de guerre de corps à corps",
         "Dégâts : 1d8 contondant.",
         "10 po", "1 kg"),
    item("Voulge", "Glaive",
         "Arme de guerre de corps à corps",
         "Dégâts : 1d10 tranchant. Propriétés : lourde, allonge, à deux mains.",
         "20 po", "3 kg"),
    item("Hache à deux mains", "Greataxe",
         "Arme de guerre de corps à corps",
         "Dégâts : 1d12 tranchant. Propriétés : lourde, à deux mains.",
         "30 po", "3,5 kg"),
    item("Espadon", "Greatsword",
         "Arme de guerre de corps à corps",
         "Dégâts : 2d6 tranchant. Propriétés : lourde, à deux mains.",
         "50 po", "3 kg"),
    item("Hallebarde", "Halberd",
         "Arme de guerre de corps à corps",
         "Dégâts : 1d10 tranchant. Propriétés : lourde, allonge, à deux mains.",
         "20 po", "3 kg"),
    item("Lance de cavalerie", "Lance",
         "Arme de guerre de corps à corps",
         "Dégâts : 1d12 perforant. Propriétés : allonge. Désavantage si cible adjacente ou sans monture.",
         "10 po", "3 kg"),
    item("Épée longue", "Longsword",
         "Arme de guerre de corps à corps",
         "Dégâts : 1d8 tranchant. Propriétés : polyvalente (1d10).",
         "15 po", "1,5 kg"),
    item("Maul", "Maul",
         "Arme de guerre de corps à corps",
         "Dégâts : 2d6 contondant. Propriétés : lourde, à deux mains.",
         "10 po", "5 kg"),
    item("Morgenstern", "Morningstar",
         "Arme de guerre de corps à corps",
         "Dégâts : 1d8 perforant.",
         "15 po", "2 kg"),
    item("Pique", "Pike",
         "Arme de guerre de corps à corps",
         "Dégâts : 1d10 perforant. Propriétés : lourde, allonge, à deux mains.",
         "5 po", "9 kg"),
    item("Rapière", "Rapier",
         "Arme de guerre de corps à corps",
         "Dégâts : 1d8 perforant. Propriétés : finesse.",
         "25 po", "1 kg"),
    item("Cimeterre", "Scimitar",
         "Arme de guerre de corps à corps",
         "Dégâts : 1d6 tranchant. Propriétés : finesse, légère.",
         "25 po", "1,5 kg"),
    item("Épée courte", "Shortsword",
         "Arme de guerre de corps à corps",
         "Dégâts : 1d6 perforant. Propriétés : finesse, légère.",
         "10 po", "1 kg"),
    item("Trident", "Trident",
         "Arme de guerre de corps à corps",
         "Dégâts : 1d6 perforant. Propriétés : lancer (portée 6/18 m), polyvalente (1d8).",
         "5 po", "2 kg"),
    item("Pic de guerre", "War Pick",
         "Arme de guerre de corps à corps",
         "Dégâts : 1d8 perforant.",
         "5 po", "1 kg"),
    item("Marteau de guerre", "Warhammer",
         "Arme de guerre de corps à corps",
         "Dégâts : 1d8 contondant. Propriétés : polyvalente (1d10).",
         "15 po", "2 kg"),
    item("Fouet", "Whip",
         "Arme de guerre de corps à corps",
         "Dégâts : 1d4 tranchant. Propriétés : finesse, allonge.",
         "2 po", "1,5 kg"),

    # ─── ARMES DE GUERRE À DISTANCE ────────────────────────────────────────
    item("Sarbacane", "Blowgun",
         "Arme de guerre à distance",
         "Dégâts : 1 perforant. Propriétés : munitions (portée 7,5/30 m), chargement.",
         "10 po", "0,5 kg"),
    item("Arbalète de poing", "Hand Crossbow",
         "Arme de guerre à distance",
         "Dégâts : 1d6 perforant. Propriétés : légère, munitions (portée 9/36 m), chargement.",
         "75 po", "1,5 kg"),
    item("Arbalète lourde", "Heavy Crossbow",
         "Arme de guerre à distance",
         "Dégâts : 1d10 perforant. Propriétés : lourde, munitions (portée 30/120 m), chargement, à deux mains.",
         "50 po", "9 kg"),
    item("Arc long", "Longbow",
         "Arme de guerre à distance",
         "Dégâts : 1d8 perforant. Propriétés : lourde, munitions (portée 45/180 m), à deux mains.",
         "50 po", "1 kg"),
    item("Filet", "Net",
         "Arme de guerre à distance",
         "Dégâts : —. Propriétés : spécial, lancer (portée 1,5/4,5 m). Entrave la cible (DD 10 de Force pour se libérer).",
         "1 po", "1,5 kg"),

    # ─── MUNITIONS ──────────────────────────────────────────────────────────
    item("Flèches (20)", "Arrows (20)",
         "Munitions",
         "Munitions pour arcs. Récupérables après combat.",
         "1 po", "0,5 kg"),
    item("Carreaux d'arbalète (20)", "Crossbow Bolts (20)",
         "Munitions",
         "Munitions pour arbalètes. Récupérables après combat.",
         "1 po", "0,75 kg"),
    item("Dards de sarbacane (50)", "Blowgun Needles (50)",
         "Munitions",
         "Munitions pour sarbacane.",
         "1 po", "0,5 kg"),
    item("Balles de fronde (20)", "Sling Bullets (20)",
         "Munitions",
         "Munitions pour fronde.",
         "4 pc", "0,75 kg"),

    # ─── ARMURES LÉGÈRES ───────────────────────────────────────────────────
    item("Gambison", "Padded Armor",
         "Armure légère",
         "CA : 11 + modificateur de Dextérité. Désavantage aux jets de Discrétion.",
         "5 po", "4 kg"),
    item("Armure de cuir", "Leather Armor",
         "Armure légère",
         "CA : 11 + modificateur de Dextérité.",
         "10 po", "5 kg"),
    item("Armure de cuir clouté", "Studded Leather Armor",
         "Armure légère",
         "CA : 12 + modificateur de Dextérité.",
         "45 po", "6,5 kg"),

    # ─── ARMURES INTERMÉDIAIRES ────────────────────────────────────────────
    item("Armure de peaux", "Hide Armor",
         "Armure intermédiaire",
         "CA : 12 + modificateur de Dextérité (max +2).",
         "10 po", "6 kg"),
    item("Armure de crin", "Chain Shirt",
         "Armure intermédiaire",
         "CA : 13 + modificateur de Dextérité (max +2).",
         "50 po", "10 kg"),
    item("Armure d'écailles", "Scale Mail",
         "Armure intermédiaire",
         "CA : 14 + modificateur de Dextérité (max +2). Désavantage aux jets de Discrétion.",
         "50 po", "22,5 kg"),
    item("Cuirasse", "Breastplate",
         "Armure intermédiaire",
         "CA : 14 + modificateur de Dextérité (max +2).",
         "400 po", "10 kg"),
    item("Demi-plates", "Half Plate Armor",
         "Armure intermédiaire",
         "CA : 15 + modificateur de Dextérité (max +2). Désavantage aux jets de Discrétion.",
         "750 po", "20 kg"),

    # ─── ARMURES LOURDES ───────────────────────────────────────────────────
    item("Armure d'anneaux", "Ring Mail",
         "Armure lourde",
         "CA : 14. Désavantage aux jets de Discrétion.",
         "30 po", "20 kg"),
    item("Cotte de mailles", "Chain Mail",
         "Armure lourde",
         "CA : 16. Force minimum : 13. Désavantage aux jets de Discrétion.",
         "75 po", "27,5 kg"),
    item("Cotte de plates", "Splint Armor",
         "Armure lourde",
         "CA : 17. Force minimum : 15. Désavantage aux jets de Discrétion.",
         "200 po", "30 kg"),
    item("Armure de plates", "Plate Armor",
         "Armure lourde",
         "CA : 18. Force minimum : 15. Désavantage aux jets de Discrétion.",
         "1 500 po", "32,5 kg"),

    # ─── BOUCLIER ──────────────────────────────────────────────────────────
    item("Bouclier", "Shield",
         "Bouclier",
         "CA : +2. Nécessite une maîtrise des boucliers.",
         "10 po", "3 kg"),

    # ─── POTIONS & CONSOMMABLES ────────────────────────────────────────────
    item("Potion de soins", "Potion of Healing",
         "Potion",
         "Récupère 2d4+2 points de vie lorsqu'elle est bue.",
         "50 po", "—"),
    item("Potion de soins supérieurs", "Potion of Greater Healing",
         "Potion",
         "Récupère 4d4+4 points de vie lorsqu'elle est bue.",
         "100 po", "—"),
    item("Potion de soins importants", "Potion of Superior Healing",
         "Potion",
         "Récupère 8d4+8 points de vie lorsqu'elle est bue.",
         "500 po", "—"),
    item("Potion de soins suprêmes", "Potion of Supreme Healing",
         "Potion",
         "Récupère 10d4+20 points de vie lorsqu'elle est bue.",
         "5 000 po", "—"),
    item("Antidote", "Antitoxin",
         "Potion",
         "La créature qui la boit a l'avantage aux jets de sauvegarde contre le poison pendant 1 heure.",
         "50 po", "—"),
    item("Eau bénite (flasque)", "Holy Water (Flask)",
         "Potion",
         "Inflige 2d6 dégâts radiants à une créature morte-vivante ou fiélon touchée.",
         "25 po", "0,5 kg"),
    item("Huile (flasque)", "Oil (Flask)",
         "Potion",
         "Peut être versée sur le sol (surface 1,5 m) ou aspergée sur une créature. Réussite d'attaque à distance (DD 8 + Dex). Cible ou surface couverte d'huile : si enflammée, 5 dégâts de feu par round pendant 2 rounds.",
         "1 pa", "0,5 kg"),
    item("Poison de base (flacon)", "Basic Poison (Vial)",
         "Poison",
         "Peut être appliqué sur une arme ou munition (1 dose = 1 minute). Cible touchée : jet de sauvegarde de Constitution DD 10 ou état empoisonné pendant 1 heure.",
         "100 po", "—"),

    # ─── ÉQUIPEMENT D'AVENTURIER ────────────────────────────────────────────
    item("Sac à dos", "Backpack",
         "Équipement d'aventurier",
         "Capacité : 30 livres (≈ 13,5 kg) / 1 pied cube (≈ 28 litres).",
         "2 po", "2,5 kg"),
    item("Corde de chanvre (15 m)", "Hempen Rope (50 ft)",
         "Équipement d'aventurier",
         "Résistance : 2 PV, CA 11. Peut supporter jusqu'à 750 livres (≈ 340 kg).",
         "1 po", "5 kg"),
    item("Corde de soie (15 m)", "Silk Rope (50 ft)",
         "Équipement d'aventurier",
         "Résistance : 2 PV, CA 13. Plus légère que la corde de chanvre.",
         "10 po", "2,5 kg"),
    item("Torche", "Torch",
         "Équipement d'aventurier",
         "Éclaire sur 6 m (lumière vive) + 6 m (pénombre). Dure 1 heure. Inflige 1 dégât de feu si utilisée comme arme improvisée.",
         "1 pc", "0,5 kg"),
    item("Lanterne à capote", "Hooded Lantern",
         "Équipement d'aventurier",
         "Éclaire sur 9 m (lumière vive) + 9 m (pénombre). Dure 6 heures par flasque d'huile. Capote rabattable : réduit à 1,5 m de pénombre seulement.",
         "5 po", "1 kg"),
    item("Lanterne sourde", "Bullseye Lantern",
         "Équipement d'aventurier",
         "Projette un cône de lumière vive sur 18 m + 18 m de pénombre. Dure 6 heures par flasque d'huile.",
         "10 po", "1 kg"),
    item("Rations (1 jour)", "Rations (1 day)",
         "Équipement d'aventurier",
         "Nourriture séchée et compacte pour une journée : viande séchée, biscuits durs, fromage.",
         "5 pa", "1 kg"),
    item("Trousse de soins", "Healer's Kit",
         "Équipement d'aventurier",
         "10 utilisations. Action : stabilise une créature avec 0 PV sans jet de Médecine.",
         "5 po", "1,5 kg"),
    item("Grappin", "Grappling Hook",
         "Équipement d'aventurier",
         "Permet l'escalade d'une surface avec une corde. Nécessite une action pour fixer.",
         "2 po", "2 kg"),
    item("Menottes", "Manacles",
         "Équipement d'aventurier",
         "Immobilise les poignets. Echapper : Force DD 20 ou Discrétion DD 17 avec une épingle à crocheter.",
         "2 po", "3 kg"),
    item("Miroir en acier", "Steel Mirror",
         "Équipement d'aventurier",
         "Petit miroir poli permettant de regarder autour des coins ou de refléter la lumière.",
         "5 po", "0,25 kg"),
    item("Tente (2 personnes)", "Tent, Two-Person",
         "Équipement d'aventurier",
         "Abri simple pour deux personnes. Protège contre les intempéries.",
         "2 po", "10 kg"),
    item("Couverture", "Blanket",
         "Équipement d'aventurier",
         "Couverture de laine épaisse.",
         "5 pa", "1,5 kg"),
    item("Loupe", "Magnifying Glass",
         "Équipement d'aventurier",
         "Permet d'allumer un feu par beau temps. Avantage aux jets d'Arcane, d'Histoire ou de Nature pour examiner un objet de près.",
         "100 po", "—"),
    item("Boîte à amadou", "Tinderbox",
         "Équipement d'aventurier",
         "Allume un feu en une action (ou action bonus si matériaux préparés). Contient silex, briquet et amadou.",
         "5 pa", "0,5 kg"),
    item("Bougie", "Candle",
         "Équipement d'aventurier",
         "Éclaire sur 1,5 m (lumière vive) + 1,5 m (pénombre). Dure 1 heure.",
         "1 pc", "—"),
    item("Sac de couchage", "Bedroll",
         "Équipement d'aventurier",
         "Permet de dormir confortablement à l'extérieur.",
         "1 po", "3,5 kg"),
    item("Sacoche à composantes", "Component Pouch",
         "Équipement d'aventurier",
         "Contient toutes les composantes matérielles sans valeur nécessaires à l'incantation.",
         "25 po", "1 kg"),
    item("Focaliseur arcanique (cristal)", "Arcane Focus (Crystal)",
         "Équipement d'aventurier",
         "Focalisant arcanique permettant l'incantation sans composantes matérielles sans valeur.",
         "10 po", "—"),
    item("Symbole sacré (argent)", "Holy Symbol (Silver)",
         "Équipement d'aventurier",
         "Focalisant divin pour clercs et paladins. En argent gravé.",
         "5 po", "—"),
    item("Symbole sacré (or)", "Holy Symbol (Gold)",
         "Équipement d'aventurier",
         "Focalisant divin pour clercs et paladins. En or incrusté.",
         "25 po", "—"),
    item("Focaliseur druidique (totem)", "Druidic Focus (Totem)",
         "Équipement d'aventurier",
         "Focalisant pour druides : totem représentant un animal ou une plante.",
         "1 po", "—"),
    item("Pince-monseigneur", "Crowbar",
         "Équipement d'aventurier",
         "Avantage aux jets de Force pour ouvrir une porte ou un couvercle fermé.",
         "2 po", "2,5 kg"),
    item("Marteau", "Hammer",
         "Équipement d'aventurier",
         "Permet d'enfoncer des pitons. Peut servir d'arme improvisée (1d4 contondant).",
         "1 po", "1,5 kg"),
    item("Pelle", "Shovel",
         "Équipement d'aventurier",
         "Permet de creuser. Déblaye 0,5 m³ de terre par heure de travail.",
         "2 po", "2,5 kg"),
    item("Pitons (10)", "Pitons (10)",
         "Équipement d'aventurier",
         "Peuvent être enfoncés dans des fissures de roche ou de bois pour l'escalade.",
         "5 pa", "1,25 kg"),
    item("Encre (flacon)", "Ink (1 ounce bottle)",
         "Équipement d'aventurier",
         "Flacon d'encre noire pour l'écriture.",
         "10 po", "—"),
    item("Plume d'écriture", "Ink Pen",
         "Équipement d'aventurier",
         "Plume taillée pour écrire avec de l'encre.",
         "2 pc", "—"),
    item("Parchemin (feuille)", "Parchment (1 sheet)",
         "Équipement d'aventurier",
         "Feuille de parchemin vierge.",
         "1 pa", "—"),
    item("Papier (feuille)", "Paper (one sheet)",
         "Équipement d'aventurier",
         "Feuille de papier vierge.",
         "2 pa", "—"),
    item("Vêtements communs", "Common Clothes",
         "Équipement d'aventurier",
         "Tenue simple : tunique, pantalon, chaussures.",
         "5 pa", "1,5 kg"),
    item("Vêtements de voyageur", "Traveler's Clothes",
         "Équipement d'aventurier",
         "Tenue robuste pour la route : manteau, bottes solides.",
         "2 po", "2 kg"),
    item("Vêtements fins", "Fine Clothes",
         "Équipement d'aventurier",
         "Tenue élégante pour se présenter en société.",
         "15 po", "3 kg"),
    item("Vêtements de cérémonie", "Ceremonial Clothes",
         "Équipement d'aventurier",
         "Tenue somptueuse pour grandes occasions.",
         "115 po", "—"),
    item("Carquois", "Quiver",
         "Équipement d'aventurier",
         "Contient jusqu'à 20 flèches.",
         "1 po", "0,5 kg"),
    item("Étui à carreaux", "Crossbow Bolt Case",
         "Équipement d'aventurier",
         "Contient jusqu'à 20 carreaux d'arbalète.",
         "1 po", "0,5 kg"),
    item("Acide (flasque)", "Acid (Vial)",
         "Équipement d'aventurier",
         "Comme action, peut être aspergé sur une créature (1,5 m). Attaque à distance DD 8+Dex. En cas de succès : 2d6 dégâts d'acide.",
         "25 po", "—"),
    item("Feu grégeois (flasque)", "Alchemist's Fire (Flask)",
         "Équipement d'aventurier",
         "Comme action, peut être lancé (1,5 m). Attaque à distance DD 8+Dex. En cas de succès : 1d4 feu par round. Action pour éteindre (DD 10 Dex).",
         "50 po", "0,5 kg"),
    item("Billes (sac de 1 000)", "Ball Bearings (Bag of 1,000)",
         "Équipement d'aventurier",
         "Peut être répandu sur 3 m × 3 m. Marcher dans la zone : jet de sauvegarde de Dex DD 10 ou tomber à terre.",
         "1 po", "1 kg"),
    item("Caltropes (sac de 20)", "Caltrops (Bag of 20)",
         "Équipement d'aventurier",
         "Peut être répandu (5 m²). Traverser la zone : jet de sauvegarde de Dex DD 15 ou 1 dégât perforant et vitesse réduite de 3 m jusqu'à guérison.",
         "1 po", "1 kg"),
    item("Chaîne (3 m)", "Chain (10 ft.)",
         "Équipement d'aventurier",
         "Résistance : 10 PV. Peut être brisée avec un jet de Force DD 20.",
         "5 po", "5 kg"),

    # ─── MATÉRIEL D'ÉCRITURE / INSTRUMENTS ─────────────────────────────────
    item("Livre vierge", "Book",
         "Équipement d'aventurier",
         "Livre de 200 pages de parchemin vierge.",
         "25 po", "2,5 kg"),
    item("Boîte de peinture", "Painter's Supplies",
         "Outil d'artisan",
         "Matériel de peintre : pinceaux, pigments, huiles.",
         "10 po", "2,5 kg"),

    # ─── OUTILS D'ARTISAN ──────────────────────────────────────────────────
    item("Matériel d'alchimiste", "Alchemist's Supplies",
         "Outil d'artisan",
         "Permet de créer des antidotes, des acides et d'autres substances alchimiques.",
         "50 po", "4 kg"),
    item("Matériel de brasseur", "Brewer's Supplies",
         "Outil d'artisan",
         "Permet de brasser de la bière, de l'hydromel et autres boissons fermentées.",
         "20 po", "4,5 kg"),
    item("Matériel de calligraphe", "Calligrapher's Supplies",
         "Outil d'artisan",
         "Permet de copier des textes avec une belle écriture.",
         "10 po", "2,5 kg"),
    item("Matériel de menuisier", "Carpenter's Tools",
         "Outil d'artisan",
         "Permet de construire et réparer des structures en bois.",
         "8 po", "3 kg"),
    item("Matériel de cartographe", "Cartographer's Tools",
         "Outil d'artisan",
         "Permet de créer des cartes et de les lire avec précision.",
         "15 po", "3 kg"),
    item("Matériel de cordonnier", "Cobbler's Tools",
         "Outil d'artisan",
         "Permet de fabriquer et réparer des chaussures.",
         "5 po", "2,5 kg"),
    item("Matériel de cuisinier", "Cook's Utensils",
         "Outil d'artisan",
         "Permet de préparer des repas et d'identifier des ingrédients.",
         "1 po", "4 kg"),
    item("Matériel de forgeron", "Smith's Tools",
         "Outil d'artisan",
         "Permet de forger des armes, armures et objets métalliques.",
         "20 po", "4 kg"),
    item("Matériel de joaillier", "Jeweler's Tools",
         "Outil d'artisan",
         "Permet de travailler les pierres précieuses et les métaux fins.",
         "25 po", "1 kg"),
    item("Matériel de maçon", "Mason's Tools",
         "Outil d'artisan",
         "Permet de travailler la pierre.",
         "10 po", "4 kg"),
    item("Matériel de potier", "Potter's Tools",
         "Outil d'artisan",
         "Permet de fabriquer de la céramique.",
         "10 po", "1,5 kg"),
    item("Matériel de tanneur", "Leatherworker's Tools",
         "Outil d'artisan",
         "Permet de travailler le cuir.",
         "5 po", "2,5 kg"),
    item("Matériel de tisseur", "Weaver's Tools",
         "Outil d'artisan",
         "Permet de tisser du tissu.",
         "1 po", "2,5 kg"),
    item("Matériel de tonnelier", "Woodcarver's Tools",
         "Outil d'artisan",
         "Permet de tailler le bois.",
         "1 po", "2,5 kg"),

    # ─── OUTILS DE JEU ─────────────────────────────────────────────────────
    item("Matériel de déguisement", "Disguise Kit",
         "Outil",
         "Permet de créer des déguisements convaincants avec maquillage, perruques et costumes.",
         "25 po", "1.5 kg"),
    item("Matériel de faussaire", "Forgery Kit",
         "Outil",
         "Permet de créer des faux documents.",
         "15 po", "1 kg"),
    item("Outils de voleur", "Thieves' Tools",
         "Outil",
         "Permettent de crocheter des serrures et désarmer des pièges. Inclus : pince-nez, miroir, ciseaux, lime et pincettes.",
         "25 po", "0,5 kg"),
    item("Matériel de navigation", "Navigator's Tools",
         "Outil",
         "Permettent de tracer une route maritime ou terrestre avec boussole, règle et cartes.",
         "25 po", "1 kg"),
    item("Matériel d'empoisonneur", "Poisoner's Kit",
         "Outil",
         "Permettent de créer des poisons et d'identifier des substances toxiques.",
         "50 po", "1 kg"),
    item("Dés à jouer", "Dice Set",
         "Outil",
         "Jeu de dés pour les jeux d'argent.",
         "1 pa", "—"),
    item("Cartes à jouer", "Playing Card Set",
         "Outil",
         "Jeu de cartes pour les jeux d'argent.",
         "5 pa", "—"),
    item("Jeu de Dragonchets", "Three-Dragon Ante Set",
         "Outil",
         "Jeu de cartes populaire dans les tavernes.",
         "1 po", "—"),

    # ─── INSTRUMENTS DE MUSIQUE ─────────────────────────────────────────────
    item("Cornemuse", "Bagpipes",
         "Instrument de musique",
         "Instrument à vent complexe originaire des hauts plateaux.",
         "30 po", "3 kg"),
    item("Luth", "Lute",
         "Instrument de musique",
         "Instrument à cordes pincées à la sonorité douce.",
         "35 po", "1 kg"),
    item("Flûte", "Flute",
         "Instrument de musique",
         "Instrument à vent simple.',",
         "2 po", "0,5 kg"),
    item("Tambour", "Drum",
         "Instrument de musique",
         "Instrument à percussion.",
         "6 po", "1,5 kg"),
    item("Cor", "Horn",
         "Instrument de musique",
         "Instrument à vent grave, utilisé pour les signaux militaires.",
         "3 po", "1 kg"),
    item("Viole", "Viol",
         "Instrument de musique",
         "Instrument à cordes frottées à l'archet, ancêtre du violon.",
         "30 po", "1 kg"),

    # ─── MONTURES ───────────────────────────────────────────────────────────
    item("Cheval de monte", "Riding Horse",
         "Monture",
         "Taille : Grande. Vitesse : 18 m. CA : 10. PV : 13. Force : 16. Charge : 240 kg.",
         "75 po", "—"),
    item("Cheval de trait", "Draft Horse",
         "Monture",
         "Taille : Grande. Vitesse : 12 m. CA : 10. PV : 19. Force : 18. Charge : 295 kg.",
         "50 po", "—"),
    item("Destrier", "Warhorse",
         "Monture",
         "Taille : Grande. Vitesse : 18 m. CA : 11. PV : 19. Force : 18. Entraîné au combat.",
         "400 po", "—"),
    item("Mulet", "Mule",
         "Monture",
         "Taille : Moyenne. Vitesse : 12 m. CA : 10. PV : 11. Force : 14. Charge : 210 kg. Terrain difficile.",
         "8 po", "—"),
    item("Poney", "Pony",
         "Monture",
         "Taille : Moyenne. Vitesse : 12 m. CA : 10. PV : 11. Force : 15.",
         "30 po", "—"),
    item("Chameau", "Camel",
         "Monture",
         "Taille : Grande. Vitesse : 15 m. CA : 9. PV : 15. Force : 16. Idéal pour le désert.",
         "50 po", "—"),

    # ─── ÉQUIPEMENT MONTURE ─────────────────────────────────────────────────
    item("Selle de voyage", "Riding Saddle",
         "Équipement de monture",
         "Selle standard pour monture. Avantage pour rester en selle.",
         "10 po", "12,5 kg"),
    item("Selle de guerre", "Military Saddle",
         "Équipement de monture",
         "Selle robuste pour le combat monté. Avantage pour rester en selle.",
         "20 po", "15 kg"),
    item("Sacoches de selle", "Saddlebags",
         "Équipement de monture",
         "Capacité : 2 × 15 kg (une de chaque côté).",
         "4 po", "4 kg"),
    item("Mors et bride", "Bit and Bridle",
         "Équipement de monture",
         "Nécessaire pour diriger une monture.",
         "2 po", "0,5 kg"),

    # ─── VÉHICULES ──────────────────────────────────────────────────────────
    item("Chariot", "Cart",
         "Véhicule terrestre",
         "Véhicule à deux roues tracté par une monture. Charge : 200 kg.",
         "15 po", "—"),
    item("Charrette", "Wagon",
         "Véhicule terrestre",
         "Véhicule à quatre roues tracté par deux montures. Charge : 400 kg.",
         "35 po", "—"),
    item("Barque", "Rowboat",
         "Véhicule nautique",
         "Petite embarcation à rames. Vitesse : 2,4 km/h. Capacité : 3 personnes.",
         "50 po", "—"),
    item("Voilier", "Sailing Ship",
         "Véhicule nautique",
         "Grand navire marchand. Vitesse : 4 km/h. Équipage : 20. Passagers : 20.",
         "10 000 po", "—"),
]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("-o", "--output", default="aidedd_standard_items.json")
    args = parser.parse_args()

    payload = {
        "source_list_url": "https://www.aidedd.org/regles/",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "count": len(ITEMS),
        "items": ITEMS,
    }

    with open(args.output, "w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)

    print(f"Generated {len(ITEMS)} standard items -> {args.output}")

    # Category summary
    from collections import Counter
    cats = Counter(i["item_type"] for i in ITEMS)
    for cat, count in sorted(cats.items()):
        print(f"  {cat}: {count}")


if __name__ == "__main__":
    main()

