/**
 * Demo account management.
 *
 * The demo account has is_demo=true in the admins table.
 * Its session always uses code '0000' — this code is reserved and never
 * generated by normal session logic (which generates 1000-9999).
 *
 * Behaviour controlled by env vars:
 *   DEMO_ENABLED       (default: true)  — set to 'false' to disable the demo account entirely
 *   DEMO_SEED_ENABLED  (default: true)  — set to 'false' to skip seeding at startup
 *   DEMO_RESET_ENABLED (default: true)  — set to 'false' to disable the nightly midnight reset
 */

const pool = require('./db')
const path = require('path')
const fs = require('fs')

const DEMO_SESSION_CODE = '0000'
const DATA_DEMO_DIR = path.join(__dirname, 'data', 'demo')
const UPLOADS_DIR = path.join(__dirname, '..', 'uploads')

const DEMO_ITEMS = [
  { name: 'Potion de soins',              description: 'Récupère 2d4+2 PV.',                                               price:  50, stock:  10, category: 'Potions'     },
  { name: 'Potion de soins supérieure',   description: 'Récupère 4d4+4 PV.',                                               price: 150, stock:   5, category: 'Potions'     },
  { name: 'Antidote',                     description: 'Neutralise les effets du poison.',                                 price:  50, stock:   5, category: 'Potions'     },
  { name: 'Torche',                       description: 'Éclaire dans un rayon de 6 m pendant 1 heure.',                   price:   1, stock:  -1, category: 'Équipement'  },
  { name: 'Corde de chanvre',             description: '15 mètres. Résistance jusqu\'à 2 tonnes.',                        price:   1, stock:  -1, category: 'Équipement'  },
  { name: 'Rations de voyage',            description: 'Nourriture séchée et conservée pour 1 journée d\'aventure.',      price:   5, stock:  -1, category: 'Équipement'  },
  { name: 'Parchemin de Soin des Blessures', description: 'Permet de lancer le sort Soin des Blessures une seule fois.',  price:  75, stock:   3, category: 'Parchemins'  },
]

// Demo assets: { srcFile, destFile, sessionImageType, originalName, audioCategory? }
const DEMO_ASSETS = [
  { srcFile: 'carte_donjon_demo.png', destFile: 'demo_carte_donjon.png', sessionImageType: 'map',   originalName: 'Carte donjon démo.png' },
  { srcFile: 'pnj1.png',             destFile: 'demo_pnj1.png',          sessionImageType: 'image', originalName: 'PNJ1.png' },
  { srcFile: 'pnj2.png',             destFile: 'demo_pnj2.png',          sessionImageType: 'image', originalName: 'PNJ2.png' },
  { srcFile: 'pnj3.png',             destFile: 'demo_pnj3.png',          sessionImageType: 'image', originalName: 'PNJ3.png' },
  { srcFile: 'campfire.mp3',         destFile: 'demo_campfire.mp3',       sessionImageType: 'audio', originalName: 'Campfire.mp3',    audioCategory: 'Ambiance' },
  { srcFile: 'growl.mp3',            destFile: 'demo_growl.mp3',          sessionImageType: 'audio', originalName: 'Growl.mp3',       audioCategory: 'Effet'    },
  { srcFile: 'town-music.mp3',       destFile: 'demo_town-music.mp3',     sessionImageType: 'audio', originalName: 'Town Music.mp3',  audioCategory: 'Musique'  },
]

/**
 * Copies demo asset files into the uploads directory for the given admin.
 * Returns a map of { destFile -> url } for each asset.
 */
async function copyDemoAssets(demoAdminId) {
  const uploadDir = path.join(UPLOADS_DIR, String(demoAdminId))
  await fs.promises.mkdir(uploadDir, { recursive: true })

  const urlMap = {}
  for (const asset of DEMO_ASSETS) {
    const src = path.join(DATA_DEMO_DIR, asset.srcFile)
    const dest = path.join(uploadDir, asset.destFile)
    await fs.promises.copyFile(src, dest)
    urlMap[asset.destFile] = `/uploads/${demoAdminId}/${asset.destFile}`
  }
  return urlMap
}

/**
 * Seeds the demo account with initial content. Idempotent — does nothing if
 * a session with code '0000' for this admin already exists.
 * @param {number} demoAdminId
 */
async function seedDemoContent(demoAdminId) {
  const existing = await pool.query(
    'SELECT id FROM sessions WHERE code = $1 AND created_by = $2',
    [DEMO_SESSION_CODE, demoAdminId]
  )
  if (existing.rows.length > 0) return

  // Copy asset files to the uploads directory
  const urlMap = await copyDemoAssets(demoAdminId)
  const mapUrl = urlMap['demo_carte_donjon.png']

  // Create demo session (map pre-loaded)
  const sessionResult = await pool.query(
    `INSERT INTO sessions (code, name, created_by, status, current_map_url)
     VALUES ($1, $2, $3, 'active', $4) RETURNING id`,
    [DEMO_SESSION_CODE, 'Campagne de démonstration', demoAdminId, mapUrl]
  )
  const sessionId = sessionResult.rows[0].id

  // Register all assets in session_images
  for (const asset of DEMO_ASSETS) {
    const url = urlMap[asset.destFile]
    if (asset.audioCategory) {
      await pool.query(
        'INSERT INTO session_images (session_id, url, original_name, type, audio_category) VALUES ($1, $2, $3, $4, $5)',
        [sessionId, url, asset.originalName, asset.sessionImageType, asset.audioCategory]
      )
    } else {
      await pool.query(
        'INSERT INTO session_images (session_id, url, original_name, type) VALUES ($1, $2, $3, $4)',
        [sessionId, url, asset.originalName, asset.sessionImageType]
      )
    }
  }

  // Create demo merchant
  const merchantResult = await pool.query(
    `INSERT INTO merchants (session_id, name, description)
     VALUES ($1, $2, $3) RETURNING id`,
    [
      sessionId,
      'Elara la Marchande',
      "Une elfe aux yeux d'ambre, spécialisée en potions et équipements d'aventuriers.",
    ]
  )
  const merchantId = merchantResult.rows[0].id

  for (const item of DEMO_ITEMS) {
    await pool.query(
      `INSERT INTO merchant_items (merchant_id, name, description, price, stock, category)
       VALUES ($1, $2, $3, $4, $5, $6)`,
      [merchantId, item.name, item.description, item.price, item.stock, item.category]
    )
  }

  console.log('[Demo] Content seeded — session code: 0000')
}

/**
 * Deletes all content owned by the demo admin (in FK order), clears uploaded
 * files, then re-seeds fresh demo content.
 * @param {number} demoAdminId
 * @param {import('socket.io').Server} [io]  Optional — if supplied, connected clients are notified before the wipe.
 */
async function resetDemoContent(demoAdminId, io) {
  try {
    console.log('[Demo] Starting nightly reset…')

    // Notify connected clients before wiping
    if (io) {
      const sessionsResult = await pool.query(
        'SELECT id FROM sessions WHERE created_by = $1', [demoAdminId]
      )
      for (const row of sessionsResult.rows) {
        io.to(`session:${row.id}`).emit('demo-reset', {
          message: 'La session de démonstration a été réinitialisée. Veuillez recharger la page.',
        })
        io.to(`admin:${row.id}`).emit('demo-reset', {
          message: 'La session de démonstration a été réinitialisée. Veuillez recharger la page.',
        })
        io.to(`tv:${row.id}`).emit('demo-reset', {
          message: 'La session de démonstration a été réinitialisée.',
        })
      }
      // Small delay so clients can receive the event before socket rooms are destroyed
      await new Promise(r => setTimeout(r, 1000))
    }

    // Delete in FK-safe order
    await pool.query(`
      DELETE FROM purchase_requests
      WHERE session_id IN (SELECT id FROM sessions WHERE created_by = $1)
    `, [demoAdminId])

    await pool.query(`
      DELETE FROM vote_responses
      WHERE vote_id IN (
        SELECT id FROM votes
        WHERE session_id IN (SELECT id FROM sessions WHERE created_by = $1)
      )
    `, [demoAdminId])

    // NULL out current_vote_id before deleting votes (FK constraint)
    await pool.query(`
      UPDATE sessions SET current_vote_id = NULL
      WHERE created_by = $1
    `, [demoAdminId])

    await pool.query(`
      DELETE FROM votes
      WHERE session_id IN (SELECT id FROM sessions WHERE created_by = $1)
    `, [demoAdminId])


    await pool.query(`
      DELETE FROM merchants
      WHERE session_id IN (SELECT id FROM sessions WHERE created_by = $1)
    `, [demoAdminId])

    await pool.query(`
      DELETE FROM session_events
      WHERE session_id IN (SELECT id FROM sessions WHERE created_by = $1)
    `, [demoAdminId])

    await pool.query(`
      DELETE FROM messages
      WHERE session_id IN (SELECT id FROM sessions WHERE created_by = $1)
    `, [demoAdminId])

    await pool.query(`
      DELETE FROM dice_results
      WHERE session_id IN (SELECT id FROM sessions WHERE created_by = $1)
    `, [demoAdminId])

    await pool.query(`
      DELETE FROM session_images
      WHERE session_id IN (SELECT id FROM sessions WHERE created_by = $1)
    `, [demoAdminId])

    await pool.query(`
      DELETE FROM players
      WHERE session_id IN (SELECT id FROM sessions WHERE created_by = $1)
    `, [demoAdminId])

    await pool.query('DELETE FROM sessions WHERE created_by = $1', [demoAdminId])

    // Remove uploaded files for the demo account (will be re-created by seedDemoContent)
    const uploadDir = path.join(UPLOADS_DIR, String(demoAdminId))
    await fs.promises.rm(uploadDir, { recursive: true, force: true })

    // Re-seed fresh content
    await seedDemoContent(demoAdminId)

    console.log('[Demo] Reset complete at', new Date().toISOString())
  } catch (err) {
    console.error('[Demo] Reset failed:', err)
  }
}

/**
 * Schedules a daily reset at midnight (local server time).
 * Uses setTimeout to the next midnight, then setInterval every 24 h.
 * No external dependencies.
 * @param {number} demoAdminId
 * @param {import('socket.io').Server} [io]
 */
function scheduleDemoReset(demoAdminId, io) {
  const now = new Date()
  const midnight = new Date(now)
  midnight.setHours(24, 0, 0, 0) // next midnight
  const msUntilMidnight = midnight - now

  console.log(`[Demo] Nightly reset scheduled in ${Math.round(msUntilMidnight / 60000)} min`)

  setTimeout(() => {
    resetDemoContent(demoAdminId, io)
    setInterval(() => resetDemoContent(demoAdminId, io), 24 * 60 * 60 * 1000)
  }, msUntilMidnight)
}

module.exports = { seedDemoContent, resetDemoContent, scheduleDemoReset }

